### ISSUE TITLE
Set up: Email API (Sendgrid)

### ISSUE THREAD

**Issue by dproc96** [hatchways/team-sparta#31]
<https://sendgrid.com/solutions/email-api/>

**Comment by vicscherman** [comment]
Generated API key, ran test setup script without error. Anything else for this task?

**Comment by vicscherman** [comment]
<img width="956" alt="Screen Shot 2021-06-07 at 12 14 56 PM" src="https://user-images.githubusercontent.com/69362301/121054084-00564480-c78a-11eb-860b-a9bfcf30ab6a.png">

![Screen Shot 2021-06-07 at 12 15 22 PM](https://user-images.githubusercontent.com/69362301/121054166-16640500-c78a-11eb-9ff5-1fc494f0444d.png)

**Comment by vicscherman** [comment]
Test email sending from project back end when it receives a post request to /email/sendemail
